env:
  commonjs: true
  es6: true
  node: true
extends: 'airbnb'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
  no-underscore-dangle: off,
  no-param-reassign: off,
  arrow-parens: off,
}